sudo: required

services:
    - docker

before_install:
    - docker build -t sdhegde/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sdhegde/react-test npm test

after_success:
    - docker build -t sdhegde/multi-client ./client
    - docker build -t sdhegde/multi-nginx ./nginx
    - docker build -t sdhegde/multi-server ./server
    - docker build -t sdhegde/multi-worker ./worker
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take the images and push to docker hub
    - docker push sdhegde/multi-client
    - docker push sdhegde/multi-nginx
    - docker push sdhegde/multi-server
    - docker push sdhegde/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-580691911971
    bucket_path: docker-multi
    on:
      brach: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY





